# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: trendlinks
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: trendlinks
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: trendlinks
  username: root
  password: root
  pool: 5
  timeout: 5000
